export type OnboardingOption = {
  id: string;
  label: string;
};

export const maxGenreSelections = 5;

export const genreOptions: OnboardingOption[] = [
  { id: 'rock', label: '록 (Rock)' },
  { id: 'pop-band', label: '팝 밴드(Pop Band)' },
  { id: 'indie', label: '인디 (Indie)' },
  { id: 'metal', label: '메탈 (Metal)' },
  { id: 'punk', label: '펑크 (Punk)' },
  { id: 'jazz-band', label: '재즈밴드 (Jazz Band)' },
  { id: 'blues', label: '블루스 (Blues)' },
  { id: 'acoustic', label: '어쿠스틱 (Acoustic)' },
  { id: 'pop-rock', label: '팝 록 (Pop Rock)' },
  { id: 'alternative-rock', label: '얼터너티브 록 (Alternative Rock)' },
  { id: 'progressive-rock', label: '프로그레시브 록 (Progressive Rock)' },
  { id: 'emo', label: '이모 (Emo)' },
  { id: 'indie-rock', label: '인디 록 (Indie Rock)' },
  { id: 'hard-rock', label: '하드 록 (Hard Rock)' },
  { id: 'post-rock', label: '포스트 록 (Post Rock)' },
  { id: 'heavy-metal', label: '헤비 메탈 (Heavy Metal)' },
  { id: 'metalcore', label: '메탈코어 (Metalcore)' },
  { id: 'punk-rock', label: '펑크 록 (Punk Rock)' },
  { id: 'funk', label: '펑크 (Funk)' },
  { id: 'soul-rnb', label: '소울 / R&B' },
  { id: 'dream-pop', label: '드림 팝 (Dream Pop)' },
  { id: 'shoegaze', label: '슈게이징 (Shoegaze)' },
  { id: 'electronic-rock', label: '일렉트로닉 록 (Electronic Rock)' },
  { id: 'synth-pop-band', label: '신스팝 밴드 (Synth Pop Band)' },
  { id: 'post-punk', label: '포스트 펑크 (Post Punk)' },
];

export const partOptions: OnboardingOption[] = [
  { id: 'electric-guitar', label: '일렉트릭 기타' },
  { id: 'acoustic-guitar', label: '어쿠스틱 기타' },
  { id: 'classic-guitar', label: '클래식 기타' },
  { id: 'bass', label: '베이스' },
  { id: 'upright-bass', label: '업라이트 베이스' },
  { id: 'drum', label: '드럼' },
  { id: 'percussion', label: '퍼커션' },
  { id: 'djembe', label: '젬베' },
  { id: 'cajon', label: '카혼' },
  { id: 'conga', label: '콩가' },
  { id: 'bongo', label: '봉고' },
  { id: 'tambourine', label: '탬버린' },
  { id: 'shaker', label: '쉐이커' },
  { id: 'maracas', label: '마라카스' },
  { id: 'vocal', label: '보컬' },
  { id: 'chorus', label: '코러스' },
  { id: 'piano', label: '피아노' },
  { id: 'keyboard', label: '키보드' },
  { id: 'synthesizer', label: '신디사이저' },
  { id: 'organ', label: '오르간' },
  { id: 'electric-piano', label: '일렉트릭 피아노' },
  { id: 'violin', label: '바이올린' },
  { id: 'viola', label: '비올라' },
  { id: 'cello', label: '첼로' },
  { id: 'contrabass', label: '콘트라베이스' },
  { id: 'harp', label: '하프' },
  { id: 'flute', label: '플루트' },
  { id: 'flute-clarinet', label: '플루트클라리넷' },
  { id: 'saxophone', label: '색소폰' },
  { id: 'trumpet', label: '트럼펫' },
  { id: 'trombone', label: '트롬본' },
  { id: 'tuba', label: '튜바' },
  { id: 'harmonica', label: '하모니카' },
  { id: 'accordion', label: '아코디언' },
  { id: 'mandolin', label: '만돌린' },
  { id: 'ukulele', label: '우쿨렐레' },
  { id: 'banjo', label: '밴조' },
];
