-- AlterEnum
-- 조성에 sharp(#) 값을 추가한다. 플랫은 이명동음이라 sharp 값으로 표현한다.
ALTER TYPE "SongKey" ADD VALUE IF NOT EXISTS 'CS';
ALTER TYPE "SongKey" ADD VALUE IF NOT EXISTS 'CSM';
ALTER TYPE "SongKey" ADD VALUE IF NOT EXISTS 'DS';
ALTER TYPE "SongKey" ADD VALUE IF NOT EXISTS 'DSM';
ALTER TYPE "SongKey" ADD VALUE IF NOT EXISTS 'FS';
ALTER TYPE "SongKey" ADD VALUE IF NOT EXISTS 'FSM';
ALTER TYPE "SongKey" ADD VALUE IF NOT EXISTS 'GS';
ALTER TYPE "SongKey" ADD VALUE IF NOT EXISTS 'GSM';
ALTER TYPE "SongKey" ADD VALUE IF NOT EXISTS 'AS';
ALTER TYPE "SongKey" ADD VALUE IF NOT EXISTS 'ASM';
