/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as ProfileRouteImport } from './pages/profile'
import { Route as AdminRouteImport } from './pages/admin'
import { Route as IndexRouteImport } from './pages/index'
import { Route as PerformanceCreateRouteImport } from './pages/performance.create'
import { Route as InviteRequestRouteImport } from './pages/invite.request'
import { Route as InviteAcceptRouteImport } from './pages/invite.accept'
import { Route as BandBandIdRouteImport } from './pages/band.$bandId'
import { Route as BandBandIdIndexRouteImport } from './pages/band.$bandId.index'
import { Route as SongSongIdTeamsRouteImport } from './pages/song.$songId.teams'
import { Route as BandBandIdSettingsRouteImport } from './pages/band.$bandId.settings'
import { Route as BandBandIdInviteRouteImport } from './pages/band.$bandId.invite'
import { Route as SongSongIdTeamTeamIdRouteImport } from './pages/song.$songId.team.$teamId'
import { Route as BandBandIdPerformancePerformanceIdRouteImport } from './pages/band.$bandId.performance.$performanceId'
import { Route as BandBandIdPerformancePerformanceIdIndexRouteImport } from './pages/band.$bandId.performance.$performanceId.index'
import { Route as BandBandIdPerformancePerformanceIdSongsRouteImport } from './pages/band.$bandId.performance.$performanceId.songs'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceCreateRoute = PerformanceCreateRouteImport.update({
  id: '/performance/create',
  path: '/performance/create',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRequestRoute = InviteRequestRouteImport.update({
  id: '/invite/request',
  path: '/invite/request',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdRoute = BandBandIdRouteImport.update({
  id: '/band/$bandId',
  path: '/band/$bandId',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdIndexRoute = BandBandIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BandBandIdRoute,
} as any)
const SongSongIdTeamsRoute = SongSongIdTeamsRouteImport.update({
  id: '/song/$songId/teams',
  path: '/song/$songId/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdSettingsRoute = BandBandIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BandBandIdRoute,
} as any)
const BandBandIdInviteRoute = BandBandIdInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => BandBandIdRoute,
} as any)
const SongSongIdTeamTeamIdRoute = SongSongIdTeamTeamIdRouteImport.update({
  id: '/song/$songId/team/$teamId',
  path: '/song/$songId/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdPerformancePerformanceIdRoute =
  BandBandIdPerformancePerformanceIdRouteImport.update({
    id: '/performance/$performanceId',
    path: '/performance/$performanceId',
    getParentRoute: () => BandBandIdRoute,
  } as any)
const BandBandIdPerformancePerformanceIdIndexRoute =
  BandBandIdPerformancePerformanceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BandBandIdPerformancePerformanceIdRoute,
  } as any)
const BandBandIdPerformancePerformanceIdSongsRoute =
  BandBandIdPerformancePerformanceIdSongsRouteImport.update({
    id: '/songs',
    path: '/songs',
    getParentRoute: () => BandBandIdPerformancePerformanceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/profile': typeof ProfileRoute
  '/band/$bandId': typeof BandBandIdRouteWithChildren
  '/invite/accept': typeof InviteAcceptRoute
  '/invite/request': typeof InviteRequestRoute
  '/performance/create': typeof PerformanceCreateRoute
  '/band/$bandId/invite': typeof BandBandIdInviteRoute
  '/band/$bandId/settings': typeof BandBandIdSettingsRoute
  '/song/$songId/teams': typeof SongSongIdTeamsRoute
  '/band/$bandId/': typeof BandBandIdIndexRoute
  '/band/$bandId/performance/$performanceId': typeof BandBandIdPerformancePerformanceIdRouteWithChildren
  '/song/$songId/team/$teamId': typeof SongSongIdTeamTeamIdRoute
  '/band/$bandId/performance/$performanceId/songs': typeof BandBandIdPerformancePerformanceIdSongsRoute
  '/band/$bandId/performance/$performanceId/': typeof BandBandIdPerformancePerformanceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/profile': typeof ProfileRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/invite/request': typeof InviteRequestRoute
  '/performance/create': typeof PerformanceCreateRoute
  '/band/$bandId/invite': typeof BandBandIdInviteRoute
  '/band/$bandId/settings': typeof BandBandIdSettingsRoute
  '/song/$songId/teams': typeof SongSongIdTeamsRoute
  '/band/$bandId': typeof BandBandIdIndexRoute
  '/song/$songId/team/$teamId': typeof SongSongIdTeamTeamIdRoute
  '/band/$bandId/performance/$performanceId/songs': typeof BandBandIdPerformancePerformanceIdSongsRoute
  '/band/$bandId/performance/$performanceId': typeof BandBandIdPerformancePerformanceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/profile': typeof ProfileRoute
  '/band/$bandId': typeof BandBandIdRouteWithChildren
  '/invite/accept': typeof InviteAcceptRoute
  '/invite/request': typeof InviteRequestRoute
  '/performance/create': typeof PerformanceCreateRoute
  '/band/$bandId/invite': typeof BandBandIdInviteRoute
  '/band/$bandId/settings': typeof BandBandIdSettingsRoute
  '/song/$songId/teams': typeof SongSongIdTeamsRoute
  '/band/$bandId/': typeof BandBandIdIndexRoute
  '/band/$bandId/performance/$performanceId': typeof BandBandIdPerformancePerformanceIdRouteWithChildren
  '/song/$songId/team/$teamId': typeof SongSongIdTeamTeamIdRoute
  '/band/$bandId/performance/$performanceId/songs': typeof BandBandIdPerformancePerformanceIdSongsRoute
  '/band/$bandId/performance/$performanceId/': typeof BandBandIdPerformancePerformanceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/profile'
    | '/band/$bandId'
    | '/invite/accept'
    | '/invite/request'
    | '/performance/create'
    | '/band/$bandId/invite'
    | '/band/$bandId/settings'
    | '/song/$songId/teams'
    | '/band/$bandId/'
    | '/band/$bandId/performance/$performanceId'
    | '/song/$songId/team/$teamId'
    | '/band/$bandId/performance/$performanceId/songs'
    | '/band/$bandId/performance/$performanceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/profile'
    | '/invite/accept'
    | '/invite/request'
    | '/performance/create'
    | '/band/$bandId/invite'
    | '/band/$bandId/settings'
    | '/song/$songId/teams'
    | '/band/$bandId'
    | '/song/$songId/team/$teamId'
    | '/band/$bandId/performance/$performanceId/songs'
    | '/band/$bandId/performance/$performanceId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/profile'
    | '/band/$bandId'
    | '/invite/accept'
    | '/invite/request'
    | '/performance/create'
    | '/band/$bandId/invite'
    | '/band/$bandId/settings'
    | '/song/$songId/teams'
    | '/band/$bandId/'
    | '/band/$bandId/performance/$performanceId'
    | '/song/$songId/team/$teamId'
    | '/band/$bandId/performance/$performanceId/songs'
    | '/band/$bandId/performance/$performanceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ProfileRoute: typeof ProfileRoute
  BandBandIdRoute: typeof BandBandIdRouteWithChildren
  InviteAcceptRoute: typeof InviteAcceptRoute
  InviteRequestRoute: typeof InviteRequestRoute
  PerformanceCreateRoute: typeof PerformanceCreateRoute
  SongSongIdTeamsRoute: typeof SongSongIdTeamsRoute
  SongSongIdTeamTeamIdRoute: typeof SongSongIdTeamTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/create': {
      id: '/performance/create'
      path: '/performance/create'
      fullPath: '/performance/create'
      preLoaderRoute: typeof PerformanceCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/request': {
      id: '/invite/request'
      path: '/invite/request'
      fullPath: '/invite/request'
      preLoaderRoute: typeof InviteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId': {
      id: '/band/$bandId'
      path: '/band/$bandId'
      fullPath: '/band/$bandId'
      preLoaderRoute: typeof BandBandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId/': {
      id: '/band/$bandId/'
      path: '/'
      fullPath: '/band/$bandId/'
      preLoaderRoute: typeof BandBandIdIndexRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/song/$songId/teams': {
      id: '/song/$songId/teams'
      path: '/song/$songId/teams'
      fullPath: '/song/$songId/teams'
      preLoaderRoute: typeof SongSongIdTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId/settings': {
      id: '/band/$bandId/settings'
      path: '/settings'
      fullPath: '/band/$bandId/settings'
      preLoaderRoute: typeof BandBandIdSettingsRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/band/$bandId/invite': {
      id: '/band/$bandId/invite'
      path: '/invite'
      fullPath: '/band/$bandId/invite'
      preLoaderRoute: typeof BandBandIdInviteRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/song/$songId/team/$teamId': {
      id: '/song/$songId/team/$teamId'
      path: '/song/$songId/team/$teamId'
      fullPath: '/song/$songId/team/$teamId'
      preLoaderRoute: typeof SongSongIdTeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId/performance/$performanceId': {
      id: '/band/$bandId/performance/$performanceId'
      path: '/performance/$performanceId'
      fullPath: '/band/$bandId/performance/$performanceId'
      preLoaderRoute: typeof BandBandIdPerformancePerformanceIdRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/band/$bandId/performance/$performanceId/': {
      id: '/band/$bandId/performance/$performanceId/'
      path: '/'
      fullPath: '/band/$bandId/performance/$performanceId/'
      preLoaderRoute: typeof BandBandIdPerformancePerformanceIdIndexRouteImport
      parentRoute: typeof BandBandIdPerformancePerformanceIdRoute
    }
    '/band/$bandId/performance/$performanceId/songs': {
      id: '/band/$bandId/performance/$performanceId/songs'
      path: '/songs'
      fullPath: '/band/$bandId/performance/$performanceId/songs'
      preLoaderRoute: typeof BandBandIdPerformancePerformanceIdSongsRouteImport
      parentRoute: typeof BandBandIdPerformancePerformanceIdRoute
    }
  }
}

interface BandBandIdPerformancePerformanceIdRouteChildren {
  BandBandIdPerformancePerformanceIdSongsRoute: typeof BandBandIdPerformancePerformanceIdSongsRoute
  BandBandIdPerformancePerformanceIdIndexRoute: typeof BandBandIdPerformancePerformanceIdIndexRoute
}

const BandBandIdPerformancePerformanceIdRouteChildren: BandBandIdPerformancePerformanceIdRouteChildren =
  {
    BandBandIdPerformancePerformanceIdSongsRoute:
      BandBandIdPerformancePerformanceIdSongsRoute,
    BandBandIdPerformancePerformanceIdIndexRoute:
      BandBandIdPerformancePerformanceIdIndexRoute,
  }

const BandBandIdPerformancePerformanceIdRouteWithChildren =
  BandBandIdPerformancePerformanceIdRoute._addFileChildren(
    BandBandIdPerformancePerformanceIdRouteChildren,
  )

interface BandBandIdRouteChildren {
  BandBandIdInviteRoute: typeof BandBandIdInviteRoute
  BandBandIdSettingsRoute: typeof BandBandIdSettingsRoute
  BandBandIdIndexRoute: typeof BandBandIdIndexRoute
  BandBandIdPerformancePerformanceIdRoute: typeof BandBandIdPerformancePerformanceIdRouteWithChildren
}

const BandBandIdRouteChildren: BandBandIdRouteChildren = {
  BandBandIdInviteRoute: BandBandIdInviteRoute,
  BandBandIdSettingsRoute: BandBandIdSettingsRoute,
  BandBandIdIndexRoute: BandBandIdIndexRoute,
  BandBandIdPerformancePerformanceIdRoute:
    BandBandIdPerformancePerformanceIdRouteWithChildren,
}

const BandBandIdRouteWithChildren = BandBandIdRoute._addFileChildren(
  BandBandIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ProfileRoute: ProfileRoute,
  BandBandIdRoute: BandBandIdRouteWithChildren,
  InviteAcceptRoute: InviteAcceptRoute,
  InviteRequestRoute: InviteRequestRoute,
  PerformanceCreateRoute: PerformanceCreateRoute,
  SongSongIdTeamsRoute: SongSongIdTeamsRoute,
  SongSongIdTeamTeamIdRoute: SongSongIdTeamTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
