/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SignupRouteImport } from './pages/signup'
import { Route as SearchRouteImport } from './pages/search'
import { Route as ProfileRouteImport } from './pages/profile'
import { Route as OnboardingRouteImport } from './pages/onboarding'
import { Route as NotificationsRouteImport } from './pages/notifications'
import { Route as MyBandsRouteImport } from './pages/my-bands'
import { Route as LoginRouteImport } from './pages/login'
import { Route as ForgotPasswordRouteImport } from './pages/forgot-password'
import { Route as AdminRouteImport } from './pages/admin'
import { Route as IndexRouteImport } from './pages/index'
import { Route as BandBandIdRouteImport } from './pages/band.$bandId'
import { Route as BandBandIdIndexRouteImport } from './pages/band.$bandId.index'
import { Route as SongSongIdTeamsRouteImport } from './pages/song.$songId.teams'
import { Route as BandBandIdSongsRouteImport } from './pages/band.$bandId.songs'
import { Route as BandBandIdSettingsRouteImport } from './pages/band.$bandId.settings'
import { Route as BandBandIdNoticesRouteImport } from './pages/band.$bandId.notices'
import { Route as BandBandIdLibraryRouteImport } from './pages/band.$bandId.library'
import { Route as BandBandIdArchiveRouteImport } from './pages/band.$bandId.archive'
import { Route as SongSongIdTeamTeamIdRouteImport } from './pages/song.$songId.team.$teamId'
import { Route as BandBandIdSpaceSpaceIdRouteImport } from './pages/band.$bandId.space.$spaceId'
import { Route as BandBandIdNoticesNoticeIdRouteImport } from './pages/band.$bandId.notices.$noticeId'
import { Route as BandBandIdSpaceSpaceIdIndexRouteImport } from './pages/band.$bandId.space.$spaceId.index'
import { Route as BandBandIdSpaceSpaceIdSettingsRouteImport } from './pages/band.$bandId.space.$spaceId.settings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBandsRoute = MyBandsRouteImport.update({
  id: '/my-bands',
  path: '/my-bands',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdRoute = BandBandIdRouteImport.update({
  id: '/band/$bandId',
  path: '/band/$bandId',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdIndexRoute = BandBandIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BandBandIdRoute,
} as any)
const SongSongIdTeamsRoute = SongSongIdTeamsRouteImport.update({
  id: '/song/$songId/teams',
  path: '/song/$songId/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdSongsRoute = BandBandIdSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => BandBandIdRoute,
} as any)
const BandBandIdSettingsRoute = BandBandIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BandBandIdRoute,
} as any)
const BandBandIdNoticesRoute = BandBandIdNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => BandBandIdRoute,
} as any)
const BandBandIdLibraryRoute = BandBandIdLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => BandBandIdRoute,
} as any)
const BandBandIdArchiveRoute = BandBandIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => BandBandIdRoute,
} as any)
const SongSongIdTeamTeamIdRoute = SongSongIdTeamTeamIdRouteImport.update({
  id: '/song/$songId/team/$teamId',
  path: '/song/$songId/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdSpaceSpaceIdRoute = BandBandIdSpaceSpaceIdRouteImport.update({
  id: '/space/$spaceId',
  path: '/space/$spaceId',
  getParentRoute: () => BandBandIdRoute,
} as any)
const BandBandIdNoticesNoticeIdRoute =
  BandBandIdNoticesNoticeIdRouteImport.update({
    id: '/$noticeId',
    path: '/$noticeId',
    getParentRoute: () => BandBandIdNoticesRoute,
  } as any)
const BandBandIdSpaceSpaceIdIndexRoute =
  BandBandIdSpaceSpaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BandBandIdSpaceSpaceIdRoute,
  } as any)
const BandBandIdSpaceSpaceIdSettingsRoute =
  BandBandIdSpaceSpaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => BandBandIdSpaceSpaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-bands': typeof MyBandsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/band/$bandId': typeof BandBandIdRouteWithChildren
  '/band/$bandId/archive': typeof BandBandIdArchiveRoute
  '/band/$bandId/library': typeof BandBandIdLibraryRoute
  '/band/$bandId/notices': typeof BandBandIdNoticesRouteWithChildren
  '/band/$bandId/settings': typeof BandBandIdSettingsRoute
  '/band/$bandId/songs': typeof BandBandIdSongsRoute
  '/song/$songId/teams': typeof SongSongIdTeamsRoute
  '/band/$bandId/': typeof BandBandIdIndexRoute
  '/band/$bandId/notices/$noticeId': typeof BandBandIdNoticesNoticeIdRoute
  '/band/$bandId/space/$spaceId': typeof BandBandIdSpaceSpaceIdRouteWithChildren
  '/song/$songId/team/$teamId': typeof SongSongIdTeamTeamIdRoute
  '/band/$bandId/space/$spaceId/settings': typeof BandBandIdSpaceSpaceIdSettingsRoute
  '/band/$bandId/space/$spaceId/': typeof BandBandIdSpaceSpaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-bands': typeof MyBandsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/band/$bandId/archive': typeof BandBandIdArchiveRoute
  '/band/$bandId/library': typeof BandBandIdLibraryRoute
  '/band/$bandId/notices': typeof BandBandIdNoticesRouteWithChildren
  '/band/$bandId/settings': typeof BandBandIdSettingsRoute
  '/band/$bandId/songs': typeof BandBandIdSongsRoute
  '/song/$songId/teams': typeof SongSongIdTeamsRoute
  '/band/$bandId': typeof BandBandIdIndexRoute
  '/band/$bandId/notices/$noticeId': typeof BandBandIdNoticesNoticeIdRoute
  '/song/$songId/team/$teamId': typeof SongSongIdTeamTeamIdRoute
  '/band/$bandId/space/$spaceId/settings': typeof BandBandIdSpaceSpaceIdSettingsRoute
  '/band/$bandId/space/$spaceId': typeof BandBandIdSpaceSpaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-bands': typeof MyBandsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/band/$bandId': typeof BandBandIdRouteWithChildren
  '/band/$bandId/archive': typeof BandBandIdArchiveRoute
  '/band/$bandId/library': typeof BandBandIdLibraryRoute
  '/band/$bandId/notices': typeof BandBandIdNoticesRouteWithChildren
  '/band/$bandId/settings': typeof BandBandIdSettingsRoute
  '/band/$bandId/songs': typeof BandBandIdSongsRoute
  '/song/$songId/teams': typeof SongSongIdTeamsRoute
  '/band/$bandId/': typeof BandBandIdIndexRoute
  '/band/$bandId/notices/$noticeId': typeof BandBandIdNoticesNoticeIdRoute
  '/band/$bandId/space/$spaceId': typeof BandBandIdSpaceSpaceIdRouteWithChildren
  '/song/$songId/team/$teamId': typeof SongSongIdTeamTeamIdRoute
  '/band/$bandId/space/$spaceId/settings': typeof BandBandIdSpaceSpaceIdSettingsRoute
  '/band/$bandId/space/$spaceId/': typeof BandBandIdSpaceSpaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/my-bands'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/signup'
    | '/band/$bandId'
    | '/band/$bandId/archive'
    | '/band/$bandId/library'
    | '/band/$bandId/notices'
    | '/band/$bandId/settings'
    | '/band/$bandId/songs'
    | '/song/$songId/teams'
    | '/band/$bandId/'
    | '/band/$bandId/notices/$noticeId'
    | '/band/$bandId/space/$spaceId'
    | '/song/$songId/team/$teamId'
    | '/band/$bandId/space/$spaceId/settings'
    | '/band/$bandId/space/$spaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/my-bands'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/signup'
    | '/band/$bandId/archive'
    | '/band/$bandId/library'
    | '/band/$bandId/notices'
    | '/band/$bandId/settings'
    | '/band/$bandId/songs'
    | '/song/$songId/teams'
    | '/band/$bandId'
    | '/band/$bandId/notices/$noticeId'
    | '/song/$songId/team/$teamId'
    | '/band/$bandId/space/$spaceId/settings'
    | '/band/$bandId/space/$spaceId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/my-bands'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/signup'
    | '/band/$bandId'
    | '/band/$bandId/archive'
    | '/band/$bandId/library'
    | '/band/$bandId/notices'
    | '/band/$bandId/settings'
    | '/band/$bandId/songs'
    | '/song/$songId/teams'
    | '/band/$bandId/'
    | '/band/$bandId/notices/$noticeId'
    | '/band/$bandId/space/$spaceId'
    | '/song/$songId/team/$teamId'
    | '/band/$bandId/space/$spaceId/settings'
    | '/band/$bandId/space/$spaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MyBandsRoute: typeof MyBandsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  BandBandIdRoute: typeof BandBandIdRouteWithChildren
  SongSongIdTeamsRoute: typeof SongSongIdTeamsRoute
  SongSongIdTeamTeamIdRoute: typeof SongSongIdTeamTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bands': {
      id: '/my-bands'
      path: '/my-bands'
      fullPath: '/my-bands'
      preLoaderRoute: typeof MyBandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId': {
      id: '/band/$bandId'
      path: '/band/$bandId'
      fullPath: '/band/$bandId'
      preLoaderRoute: typeof BandBandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId/': {
      id: '/band/$bandId/'
      path: '/'
      fullPath: '/band/$bandId/'
      preLoaderRoute: typeof BandBandIdIndexRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/song/$songId/teams': {
      id: '/song/$songId/teams'
      path: '/song/$songId/teams'
      fullPath: '/song/$songId/teams'
      preLoaderRoute: typeof SongSongIdTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId/songs': {
      id: '/band/$bandId/songs'
      path: '/songs'
      fullPath: '/band/$bandId/songs'
      preLoaderRoute: typeof BandBandIdSongsRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/band/$bandId/settings': {
      id: '/band/$bandId/settings'
      path: '/settings'
      fullPath: '/band/$bandId/settings'
      preLoaderRoute: typeof BandBandIdSettingsRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/band/$bandId/notices': {
      id: '/band/$bandId/notices'
      path: '/notices'
      fullPath: '/band/$bandId/notices'
      preLoaderRoute: typeof BandBandIdNoticesRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/band/$bandId/library': {
      id: '/band/$bandId/library'
      path: '/library'
      fullPath: '/band/$bandId/library'
      preLoaderRoute: typeof BandBandIdLibraryRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/band/$bandId/archive': {
      id: '/band/$bandId/archive'
      path: '/archive'
      fullPath: '/band/$bandId/archive'
      preLoaderRoute: typeof BandBandIdArchiveRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/song/$songId/team/$teamId': {
      id: '/song/$songId/team/$teamId'
      path: '/song/$songId/team/$teamId'
      fullPath: '/song/$songId/team/$teamId'
      preLoaderRoute: typeof SongSongIdTeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId/space/$spaceId': {
      id: '/band/$bandId/space/$spaceId'
      path: '/space/$spaceId'
      fullPath: '/band/$bandId/space/$spaceId'
      preLoaderRoute: typeof BandBandIdSpaceSpaceIdRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/band/$bandId/notices/$noticeId': {
      id: '/band/$bandId/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/band/$bandId/notices/$noticeId'
      preLoaderRoute: typeof BandBandIdNoticesNoticeIdRouteImport
      parentRoute: typeof BandBandIdNoticesRoute
    }
    '/band/$bandId/space/$spaceId/': {
      id: '/band/$bandId/space/$spaceId/'
      path: '/'
      fullPath: '/band/$bandId/space/$spaceId/'
      preLoaderRoute: typeof BandBandIdSpaceSpaceIdIndexRouteImport
      parentRoute: typeof BandBandIdSpaceSpaceIdRoute
    }
    '/band/$bandId/space/$spaceId/settings': {
      id: '/band/$bandId/space/$spaceId/settings'
      path: '/settings'
      fullPath: '/band/$bandId/space/$spaceId/settings'
      preLoaderRoute: typeof BandBandIdSpaceSpaceIdSettingsRouteImport
      parentRoute: typeof BandBandIdSpaceSpaceIdRoute
    }
  }
}

interface BandBandIdNoticesRouteChildren {
  BandBandIdNoticesNoticeIdRoute: typeof BandBandIdNoticesNoticeIdRoute
}

const BandBandIdNoticesRouteChildren: BandBandIdNoticesRouteChildren = {
  BandBandIdNoticesNoticeIdRoute: BandBandIdNoticesNoticeIdRoute,
}

const BandBandIdNoticesRouteWithChildren =
  BandBandIdNoticesRoute._addFileChildren(BandBandIdNoticesRouteChildren)

interface BandBandIdSpaceSpaceIdRouteChildren {
  BandBandIdSpaceSpaceIdSettingsRoute: typeof BandBandIdSpaceSpaceIdSettingsRoute
  BandBandIdSpaceSpaceIdIndexRoute: typeof BandBandIdSpaceSpaceIdIndexRoute
}

const BandBandIdSpaceSpaceIdRouteChildren: BandBandIdSpaceSpaceIdRouteChildren =
  {
    BandBandIdSpaceSpaceIdSettingsRoute: BandBandIdSpaceSpaceIdSettingsRoute,
    BandBandIdSpaceSpaceIdIndexRoute: BandBandIdSpaceSpaceIdIndexRoute,
  }

const BandBandIdSpaceSpaceIdRouteWithChildren =
  BandBandIdSpaceSpaceIdRoute._addFileChildren(
    BandBandIdSpaceSpaceIdRouteChildren,
  )

interface BandBandIdRouteChildren {
  BandBandIdArchiveRoute: typeof BandBandIdArchiveRoute
  BandBandIdLibraryRoute: typeof BandBandIdLibraryRoute
  BandBandIdNoticesRoute: typeof BandBandIdNoticesRouteWithChildren
  BandBandIdSettingsRoute: typeof BandBandIdSettingsRoute
  BandBandIdSongsRoute: typeof BandBandIdSongsRoute
  BandBandIdIndexRoute: typeof BandBandIdIndexRoute
  BandBandIdSpaceSpaceIdRoute: typeof BandBandIdSpaceSpaceIdRouteWithChildren
}

const BandBandIdRouteChildren: BandBandIdRouteChildren = {
  BandBandIdArchiveRoute: BandBandIdArchiveRoute,
  BandBandIdLibraryRoute: BandBandIdLibraryRoute,
  BandBandIdNoticesRoute: BandBandIdNoticesRouteWithChildren,
  BandBandIdSettingsRoute: BandBandIdSettingsRoute,
  BandBandIdSongsRoute: BandBandIdSongsRoute,
  BandBandIdIndexRoute: BandBandIdIndexRoute,
  BandBandIdSpaceSpaceIdRoute: BandBandIdSpaceSpaceIdRouteWithChildren,
}

const BandBandIdRouteWithChildren = BandBandIdRoute._addFileChildren(
  BandBandIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MyBandsRoute: MyBandsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  BandBandIdRoute: BandBandIdRouteWithChildren,
  SongSongIdTeamsRoute: SongSongIdTeamsRoute,
  SongSongIdTeamTeamIdRoute: SongSongIdTeamTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
