/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SignupRouteImport } from './pages/signup'
import { Route as ProfileRouteImport } from './pages/profile'
import { Route as LoginRouteImport } from './pages/login'
import { Route as AdminRouteImport } from './pages/admin'
import { Route as IndexRouteImport } from './pages/index'
import { Route as BandBandIdRouteImport } from './pages/band.$bandId'
import { Route as BandBandIdIndexRouteImport } from './pages/band.$bandId.index'
import { Route as SongSongIdTeamsRouteImport } from './pages/song.$songId.teams'
import { Route as BandBandIdSongsRouteImport } from './pages/band.$bandId.songs'
import { Route as BandBandIdSettingsRouteImport } from './pages/band.$bandId.settings'
import { Route as SongSongIdTeamTeamIdRouteImport } from './pages/song.$songId.team.$teamId'
import { Route as BandBandIdPerformancePerformanceIdRouteImport } from './pages/band.$bandId.performance.$performanceId'
import { Route as BandBandIdPerformancePerformanceIdIndexRouteImport } from './pages/band.$bandId.performance.$performanceId.index'
import { Route as BandBandIdPerformancePerformanceIdSettingsRouteImport } from './pages/band.$bandId.performance.$performanceId.settings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdRoute = BandBandIdRouteImport.update({
  id: '/band/$bandId',
  path: '/band/$bandId',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdIndexRoute = BandBandIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BandBandIdRoute,
} as any)
const SongSongIdTeamsRoute = SongSongIdTeamsRouteImport.update({
  id: '/song/$songId/teams',
  path: '/song/$songId/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdSongsRoute = BandBandIdSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => BandBandIdRoute,
} as any)
const BandBandIdSettingsRoute = BandBandIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BandBandIdRoute,
} as any)
const SongSongIdTeamTeamIdRoute = SongSongIdTeamTeamIdRouteImport.update({
  id: '/song/$songId/team/$teamId',
  path: '/song/$songId/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const BandBandIdPerformancePerformanceIdRoute =
  BandBandIdPerformancePerformanceIdRouteImport.update({
    id: '/performance/$performanceId',
    path: '/performance/$performanceId',
    getParentRoute: () => BandBandIdRoute,
  } as any)
const BandBandIdPerformancePerformanceIdIndexRoute =
  BandBandIdPerformancePerformanceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BandBandIdPerformancePerformanceIdRoute,
  } as any)
const BandBandIdPerformancePerformanceIdSettingsRoute =
  BandBandIdPerformancePerformanceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => BandBandIdPerformancePerformanceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/band/$bandId': typeof BandBandIdRouteWithChildren
  '/band/$bandId/settings': typeof BandBandIdSettingsRoute
  '/band/$bandId/songs': typeof BandBandIdSongsRoute
  '/song/$songId/teams': typeof SongSongIdTeamsRoute
  '/band/$bandId/': typeof BandBandIdIndexRoute
  '/band/$bandId/performance/$performanceId': typeof BandBandIdPerformancePerformanceIdRouteWithChildren
  '/song/$songId/team/$teamId': typeof SongSongIdTeamTeamIdRoute
  '/band/$bandId/performance/$performanceId/settings': typeof BandBandIdPerformancePerformanceIdSettingsRoute
  '/band/$bandId/performance/$performanceId/': typeof BandBandIdPerformancePerformanceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/band/$bandId/settings': typeof BandBandIdSettingsRoute
  '/band/$bandId/songs': typeof BandBandIdSongsRoute
  '/song/$songId/teams': typeof SongSongIdTeamsRoute
  '/band/$bandId': typeof BandBandIdIndexRoute
  '/song/$songId/team/$teamId': typeof SongSongIdTeamTeamIdRoute
  '/band/$bandId/performance/$performanceId/settings': typeof BandBandIdPerformancePerformanceIdSettingsRoute
  '/band/$bandId/performance/$performanceId': typeof BandBandIdPerformancePerformanceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/band/$bandId': typeof BandBandIdRouteWithChildren
  '/band/$bandId/settings': typeof BandBandIdSettingsRoute
  '/band/$bandId/songs': typeof BandBandIdSongsRoute
  '/song/$songId/teams': typeof SongSongIdTeamsRoute
  '/band/$bandId/': typeof BandBandIdIndexRoute
  '/band/$bandId/performance/$performanceId': typeof BandBandIdPerformancePerformanceIdRouteWithChildren
  '/song/$songId/team/$teamId': typeof SongSongIdTeamTeamIdRoute
  '/band/$bandId/performance/$performanceId/settings': typeof BandBandIdPerformancePerformanceIdSettingsRoute
  '/band/$bandId/performance/$performanceId/': typeof BandBandIdPerformancePerformanceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/signup'
    | '/band/$bandId'
    | '/band/$bandId/settings'
    | '/band/$bandId/songs'
    | '/song/$songId/teams'
    | '/band/$bandId/'
    | '/band/$bandId/performance/$performanceId'
    | '/song/$songId/team/$teamId'
    | '/band/$bandId/performance/$performanceId/settings'
    | '/band/$bandId/performance/$performanceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/signup'
    | '/band/$bandId/settings'
    | '/band/$bandId/songs'
    | '/song/$songId/teams'
    | '/band/$bandId'
    | '/song/$songId/team/$teamId'
    | '/band/$bandId/performance/$performanceId/settings'
    | '/band/$bandId/performance/$performanceId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/signup'
    | '/band/$bandId'
    | '/band/$bandId/settings'
    | '/band/$bandId/songs'
    | '/song/$songId/teams'
    | '/band/$bandId/'
    | '/band/$bandId/performance/$performanceId'
    | '/song/$songId/team/$teamId'
    | '/band/$bandId/performance/$performanceId/settings'
    | '/band/$bandId/performance/$performanceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  BandBandIdRoute: typeof BandBandIdRouteWithChildren
  SongSongIdTeamsRoute: typeof SongSongIdTeamsRoute
  SongSongIdTeamTeamIdRoute: typeof SongSongIdTeamTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId': {
      id: '/band/$bandId'
      path: '/band/$bandId'
      fullPath: '/band/$bandId'
      preLoaderRoute: typeof BandBandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId/': {
      id: '/band/$bandId/'
      path: '/'
      fullPath: '/band/$bandId/'
      preLoaderRoute: typeof BandBandIdIndexRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/song/$songId/teams': {
      id: '/song/$songId/teams'
      path: '/song/$songId/teams'
      fullPath: '/song/$songId/teams'
      preLoaderRoute: typeof SongSongIdTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId/songs': {
      id: '/band/$bandId/songs'
      path: '/songs'
      fullPath: '/band/$bandId/songs'
      preLoaderRoute: typeof BandBandIdSongsRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/band/$bandId/settings': {
      id: '/band/$bandId/settings'
      path: '/settings'
      fullPath: '/band/$bandId/settings'
      preLoaderRoute: typeof BandBandIdSettingsRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/song/$songId/team/$teamId': {
      id: '/song/$songId/team/$teamId'
      path: '/song/$songId/team/$teamId'
      fullPath: '/song/$songId/team/$teamId'
      preLoaderRoute: typeof SongSongIdTeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band/$bandId/performance/$performanceId': {
      id: '/band/$bandId/performance/$performanceId'
      path: '/performance/$performanceId'
      fullPath: '/band/$bandId/performance/$performanceId'
      preLoaderRoute: typeof BandBandIdPerformancePerformanceIdRouteImport
      parentRoute: typeof BandBandIdRoute
    }
    '/band/$bandId/performance/$performanceId/': {
      id: '/band/$bandId/performance/$performanceId/'
      path: '/'
      fullPath: '/band/$bandId/performance/$performanceId/'
      preLoaderRoute: typeof BandBandIdPerformancePerformanceIdIndexRouteImport
      parentRoute: typeof BandBandIdPerformancePerformanceIdRoute
    }
    '/band/$bandId/performance/$performanceId/settings': {
      id: '/band/$bandId/performance/$performanceId/settings'
      path: '/settings'
      fullPath: '/band/$bandId/performance/$performanceId/settings'
      preLoaderRoute: typeof BandBandIdPerformancePerformanceIdSettingsRouteImport
      parentRoute: typeof BandBandIdPerformancePerformanceIdRoute
    }
  }
}

interface BandBandIdPerformancePerformanceIdRouteChildren {
  BandBandIdPerformancePerformanceIdSettingsRoute: typeof BandBandIdPerformancePerformanceIdSettingsRoute
  BandBandIdPerformancePerformanceIdIndexRoute: typeof BandBandIdPerformancePerformanceIdIndexRoute
}

const BandBandIdPerformancePerformanceIdRouteChildren: BandBandIdPerformancePerformanceIdRouteChildren =
  {
    BandBandIdPerformancePerformanceIdSettingsRoute:
      BandBandIdPerformancePerformanceIdSettingsRoute,
    BandBandIdPerformancePerformanceIdIndexRoute:
      BandBandIdPerformancePerformanceIdIndexRoute,
  }

const BandBandIdPerformancePerformanceIdRouteWithChildren =
  BandBandIdPerformancePerformanceIdRoute._addFileChildren(
    BandBandIdPerformancePerformanceIdRouteChildren,
  )

interface BandBandIdRouteChildren {
  BandBandIdSettingsRoute: typeof BandBandIdSettingsRoute
  BandBandIdSongsRoute: typeof BandBandIdSongsRoute
  BandBandIdIndexRoute: typeof BandBandIdIndexRoute
  BandBandIdPerformancePerformanceIdRoute: typeof BandBandIdPerformancePerformanceIdRouteWithChildren
}

const BandBandIdRouteChildren: BandBandIdRouteChildren = {
  BandBandIdSettingsRoute: BandBandIdSettingsRoute,
  BandBandIdSongsRoute: BandBandIdSongsRoute,
  BandBandIdIndexRoute: BandBandIdIndexRoute,
  BandBandIdPerformancePerformanceIdRoute:
    BandBandIdPerformancePerformanceIdRouteWithChildren,
}

const BandBandIdRouteWithChildren = BandBandIdRoute._addFileChildren(
  BandBandIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  BandBandIdRoute: BandBandIdRouteWithChildren,
  SongSongIdTeamsRoute: SongSongIdTeamsRoute,
  SongSongIdTeamTeamIdRoute: SongSongIdTeamTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
